// Code generated by protoc-gen-grpc-js-client
// source: status.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function statusServiceStatus(p, conf) {
    path = '/apis/status/json'
    return xhr(path, 'GET', conf, p);
}

var services = {
    statusService: {
        status: statusServiceStatus
    }
};

module.exports = {github: {com: {appscode: {hellogrpc: {apis: {status: services}}}}}};
