FROM golang:alpine AS build
WORKDIR /go/src/github.com/appscode/hello-grpc
COPY . .
RUN go build -o /output/client ./client/go/client.go


FROM golang:alpine
WORKDIR /app
COPY --from=build /output/client .
ENTRYPOINT ["./client"]


# docker build -t diptadas/hello-client:1.0 -f Dockerfile.client .
# docker run -it diptadas/hello-client:1.0 --address=192.168.99.100:30807