// Code generated by protoc-gen-grpc-gateway-cors
// source: status.proto
// DO NOT EDIT!

/*
Package status is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package status

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportStatusServiceCorsPatterns returns an array of grpc gatway mux patterns for
// StatusService service to enable CORS.
func ExportStatusServiceCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{}
}
