// Code generated by protoc-gen-grpc-js-client
// source: hello.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function helloServiceIntro(p, conf) {
    path = '/apis/hello/v1alpha1/intro/json'
    return xhr(path, 'GET', conf, p);
}

var services = {
    helloService: {
        intro: helloServiceIntro
    }
};

module.exports = {github: {com: {appscode: {hellogrpc: {apis: {hello: {v1alpha1: services}}}}}}};
